name: Untwist
options:
  bundleIdPrefix: com.osmanseven
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_NAME: "$(TARGET_NAME)"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: 5V9A3GUJ32
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    INFOPLIST_FILE: Untwist/Info.plist

targets:
  Untwist:
    type: application
    platform: iOS
    sources:
      - path: Untwist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.osmanseven.untwist
        INFOPLIST_FILE: Untwist/Info.plist
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
