name: Untwist
options:
  bundleIdPrefix: com.osmanseven
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios-spm.git
    majorVersion: 5.0.0

settings:
  base:
    PRODUCT_NAME: "$(TARGET_NAME)"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: 5V9A3GUJ32
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    INFOPLIST_FILE: Untwist/Info.plist

targets:
  Untwist:
    type: application
    platform: iOS
    sources:
      - path: Untwist
    dependencies:
      - package: RevenueCat
        product: RevenueCat
      - package: RevenueCat
        product: RevenueCatUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.osmanseven.untwist
        INFOPLIST_FILE: Untwist/Info.plist
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"

  UntwistTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: UntwistTests
    dependencies:
      - target: Untwist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.osmanseven.untwist.tests
